### ISSUE TITLE
Error on opening workflow details in Workflow engine console

### ISSUE THREAD

**Issue by aleksei123** [zutnop/telekom-workflow-engine#5]
When any workflow that contains some instances is selected in workflow list, an error message is displayed in instances list:
DataTables warning: table id=instancesTable - Requested unknown parameter 'dateCreatedText' for row 0. For more information about this error, please see http://datatables.net/tn/4

**Comment by zutnop** [comment]
I'm going to need more information to debug this problem. This is basic
functionality and it "works in our development, test and production
machines" :)

What version of TWE are you running? Have you made modifications? What
database are you using? Can you connect to the DB and select from workflow
instances table to make sure that date-created mandatory field has value
for every row?

**Comment by aleksei123** [comment]
We are using version 1.0.2, with no modifications, PostgreSQL as database. Field date_created is filled in workflow_instances records. It is also returned

**Comment by zutnop** [comment]
Has it ever worked for you, or is it the first time you try this?

**Comment by zutnop** [comment]
Something funny with the date fields in the JSON response. Where your example has two fields in the data block:

"dateCreated":1451898553679,
"nextTimerDueDate":null,

my working example has those four fields instead:

"dateCreated":"Jan 5, 2016 11:12:27 AM",
"dateCreatedText":"05.01.2016 11:12:27:736",
"nextTimerDueDate":"Jan 12, 2016 7:00:00 PM",
"nextTimerDueDateText":"12.01.2016 19:00:00:000",

**Comment by zutnop** [comment]
TWE WorkflowInstancesListController.searchInstancesAjax returns ResponseEntity<DataTable>. This DataTable object contains the data property, which is a list of WorkflowInstanceSearchModel objects. 
WorkflowInstanceSearchModel contains instance properties:
private Date dateCreated with getter&setter
private String dateCreatedText WITHOUTH getter and setter.

My assumption is, that you are using a different version of something, not exactly sure what :). I don't know from top of my head, how Spring MVC converts the controller ResponseEntity object to JSON. Please find out what parser is used for this and why your implementation only converts the date property with getter field (into milliseconds) and why does it ignore the private text field without getter methods.

**Comment by aleksei123** [comment]
Is it possible to add getters for dateCreatedText and nextTimerDueDateText as well or there is any reason why these fields are without getters?

**Comment by aleksei123** [comment]
On our side we find it wrong to expose private fields of model objects in rest responses, so could you please add getters for those fields that do not have them yet?

**Comment by aleksei123** [comment]
Could you please publish version with this fix?

**Comment by zutnop** [comment]
This fix is included in https://github.com/zutnop/telekom-workflow-engine/releases/tag/v1.0.3
